#!/bin/sh
sleep 25
code='(crontab -l | grep -Fxq "0 * * * * /data/etc/Spotmarket-Switcher/controller.sh") || (crontab -l; echo "0 * * * * /data/etc/Spotmarket-Switcher/controller.sh") | crontab -'
code2='(crontab -l \| grep -Fxq \"0 * * * * /data/etc/Spotmarket-Switcher/controller.sh\") \|\| (crontab -l; echo \"0 * * * * /data/etc/Spotmarket-Switcher/controller.sh\") \| crontab -'
count=$(grep -Fc "$code" /data/rc.local)
if [[ $count = 0 ]]; then
#add crontab immedeately and at system start (only if it doesnt exist)
echo >> /data/rc.local
echo "$code" >> /data/rc.local
chmod +x /data/rc.local
(crontab -l | grep -Fxq "0 * * * * /data/etc/Spotmarket-Switcher/controller.sh") || (crontab -l; echo "0 * * * * /data/etc/Spotmarket-Switcher/controller.sh") | crontab -
exit 0
fi
if [[ $count = 1 ]]; then
# No need to do something, we are fine.
exit 0
fi
if [[ $count -gt 1 ]]; then
#remove double lines to correct a bug of a older version of this run script
awk '!seen[$code2]++' /data/rc.local > /data/rc.local.tmp && mv /data/rc.local.tmp /data/rc.local
chmod +x /data/rc.local
fi
