#!/bin/bash

License=$(
    cat <<EOLICENSE
  MIT License

  Copyright (c) 2023 christian1980nrw

  Permission is hereby granted, free of charge, to any person
  obtaining a copy of this software and associated documentation
  files (the "Software"), to deal in the Software without restriction,
  including without limitation the rights to use, copy, modify,
  merge, publish, distribute, sublicense, and/or sell copies of the
  Software, and to permit persons to whom the Software is furnished
  to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be
  included in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
  BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
  AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
  OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
  IN THE SOFTWARE.
EOLICENSE
)

# Stop execution upon uncaught errors
set -e

# Delaying for 25 seconds unless in DEBUG mode
if [ -z "$DEBUG" ]; then
    echo "Waiting for 25 seconds..."
    sleep 25
fi

if [ -z "$rc_local_file" ]; then
    # Define the rc.local file path
    rc_local_file="/data/rc.local"
fi

# Check if rc.local file exists, if not, create it
if [ ! -e "$rc_local_file" ]; then
    echo "#!/bin/sh" >"$rc_local_file"
    chmod +x "$rc_local_file"
fi

# Check if the code is already in rc.local, if not, add it
if ! grep -qF "$code" "$rc_local_file"; then
    {
        echo '(crontab -l | grep -Fxq "0 * * * * /data/etc/Spotmarket-Switcher/controller.sh") || (crontab -l; echo "0 * * * * /data/etc/Spotmarket-Switcher/controller.sh")'
        (crontab -l | grep -Fxq "0 * * * * /data/etc/Spotmarket-Switcher/controller.sh") || (
            crontab -l
            echo "0 * * * * /data/etc/Spotmarket-Switcher/controller.sh"
        ) | crontab -
    } | tee -a "$rc_local_file"
fi

# Display a success message in DEBUG mode
if [ -n "$DEBUG" ]; then
    echo "[ OK ]"
fi
