#!/bin/sh

License=$(cat <<EOLICENSE
MIT License

Copyright (c) 2023 christian1980nrw

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
EOLICENSE
)


# Stop execution upon uncaught errors
set -e

if [ -z "$DEBUG" ]; then
    # Delaying for 25 seconds
    sleep 25
fi

# The file found at boot time by the OS that amends the crontab to execute the controller.sh script
if [ -z "$rc_local_file" ]; then
    rc_local_file="/data/rc.local"
fi

code='(crontab -l | grep -Fxq "0 * * * * /data/etc/Spotmarket-Switcher/controller.sh") || (crontab -l; echo "0 * * * * /data/etc/Spotmarket-Switcher/controller.sh") | crontab -'
code2='(crontab -l \| grep -Fxq \"0 * * * * /data/etc/Spotmarket-Switcher/controller.sh\") \|\| (crontab -l; echo \"0 * * * * /data/etc/Spotmarket-Switcher/controller.sh\") \| crontab -'

# Count number of occurences of the code to be executed in the rc.local file
count=0
if [ -e "$rc_local_file" ]; then
    # if grep finds no matching line the return code is != 0
    count=$(grep -Fc "$code" "$rc_local_file" || echo 0)
else
    echo "#!/bin/sh" > "$rc_local_file"
    chmod +x "$rc_local_file"
fi

if [ "$count" = "0" ]; then

    # The rc.local file does not feature the instruction, yet.
    # Add crontab immediately and at system start (only if it doesnt exist)
    echo >> "$rc_local_file"
    echo "$code" >> "$rc_local_file"

    if  [ -z "$DEBUG" ]; then
        (crontab -l | grep -Fxq "0 * * * * /data/etc/Spotmarket-Switcher/controller.sh") || (crontab -l; echo "0 * * * * /data/etc/Spotmarket-Switcher/controller.sh") | crontab -
    fi

elif [ "$count" != "1" ]; then

    # Removing doublettes to correct for a bug of a older version of this run script
    awk '!seen[$code2]++' "$rc_local_file" > "$rc_local_file.tmp" && mv "$rc_local_file.tmp" "$rc_local_file"
    chmod +x "$rc_local_file"

fi

# Exit with success
if [ -n "$DEBUG" ]; then
  echo "[ OK ]"
fi
